(function(){
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const isHome=()=>/\/v18\/(?:index\.html)?$/.test(location.pathname)||location.pathname.endsWith('/v18/');
 const productId=()=>{const m=location.pathname.match(/product-(shirt|hoodie|pants|zipper)/);return m?m[1]:null};
 const evt=(name,props={})=>{if(typeof track==='function')track(name,{...props,v18:true})};
 function ready(){document.documentElement.classList.add('v18');document.body.classList.add('v18-ready')}
 function hero(){const h=$('.hero');if(!h)return;const copy=$('.hero-copy',h),title=$('#heroTitle',h),shop=$('#heroShop',h);if(title)title.innerHTML='HEAVY.<br>BY DESIGN.';if(shop)shop.textContent='SHOP FORM / MOTION';const p=$('p',copy);if(p)p.textContent='Heavyweight Streetwear mit klarer Silhouette. Entwickelt für Präsenz, Bewegung und einen Fit, der nicht beliebig wirkt.';if(!$('.v18-hero-proof',copy)){const proof=document.createElement('div');proof.className='v18-hero-proof';proof.innerHTML='<span>240–430 GSM</span><span>2–4 Werktage</span><span>30 Tage Rückgabe</span>';copy?.appendChild(proof)}evt('hero_signature_view')}
 function homeStrip(){if($('.v18-home-strip')||!$('.hero'))return;const e=document.createElement('div');e.className='v18-home-strip';e.innerHTML='<div><b>HEAVYWEIGHT</b><span>240–430 GSM je Piece</span></div><div><b>FIT INTELLIGENCE</b><span>Größe sicherer wählen</span></div><div><b>2–4 WERKTAGE</b><span>Lieferung innerhalb DE</span></div><div><b>30 TAGE</b><span>Rückgabe</span></div>';$('.hero').after(e)}
 function reorderHome(){const main=$('main');if(!main)return;const best=$('#bestsellers'),bundle=$('#bundle'),why=$('#whyHeavy'),fit=$('#fitSection'),look=$('#lookBuilder'),ugc=$('#v17Ugc'),social=$('#socialProof'),early=$('#earlyAccess');const anchor=$('.v18-home-strip')||$('.hero');if(best&&anchor)anchor.after(best);if(bundle&&best)best.after(bundle);if(why&&bundle)bundle.after(why);const story=$('#v16Story');if(story&&why)why.after(story);const manifesto=$('.v17-brand-manifesto');if(manifesto&&story)story.after(manifesto);if(fit&&manifesto)manifesto.after(fit);else if(fit&&story)story.after(fit);if(look&&fit)fit.after(look);if(ugc&&look)look.after(ugc);if(social&&ugc)ugc.after(social);if(early&&social)social.after(early)}
 function spotlight(){if($('.v18-spotlight')||!$('#bundle')||typeof PRODUCTS==='undefined')return;const p=PRODUCTS.shirt,g=p.gallery['Schwarz']||p.gallery[p.colors[0]],s=document.createElement('section');s.className='v18-spotlight';s.innerHTML=`<div class="v18-spotlight-grid"><a class="v18-spotlight-media" href="product-shirt.html"><img class="front" src="${g[0]}&width=1200" loading="lazy" width="1200" height="1500"><img class="back" src="${g[1]||g[0]}&width=1200" loading="lazy" width="1200" height="1500"></a><div class="v18-spotlight-copy"><div class="eye">HERO PRODUCT · ${p.gsm} GSM</div><h2>FORM.<br>WITH<br>WEIGHT.</h2><p>Der Formshift verbindet eine klare Oversized-Silhouette mit schwerer Baumwolle und einem ruhigen, strukturierten Fall.</p><div class="v18-value-list"><div><b>${p.gsm} GSM</b><span>spürbare Materialsubstanz</span></div><div><b>${p.fit}</b><span>klare Silhouette statt formloser Weite</span></div><div><b>2–4 Werktage</b><span>Lieferzeit innerhalb Deutschlands</span></div><div><b>30 Tage</b><span>Rückgabe für mehr Sicherheit beim Fit</span></div></div><a class="btn primary" href="product-shirt.html">FORM SHIFT ENTDECKEN</a></div></div>`;$('#bundle').after(s)}
 function proofFacts(){const social=$('#socialProof');if(!social||$('.v18-proof-facts',social))return;const h=$('h2',social),p=$('.section-head p',social);if(h)h.innerHTML='PROOF.<br>NOT PROMISES.';if(p)p.textContent='Echte Reviews, Creator-Inhalte und Fit-Daten erscheinen hier nur, wenn sie live verbunden sind. Was bereits feststeht: Material, Versand, Rückgabe und Produktdaten.';const e=document.createElement('div');e.className='v18-proof-facts';e.innerHTML='<div><b>240–430 GSM</b><span>produktabhängiges Heavyweight-Spektrum</span></div><div><b>2–4 Werktage</b><span>Lieferzeit innerhalb Deutschlands</span></div><div><b>30 Tage</b><span>Rückgabe</span></div><div><b>ab 50 €</b><span>kostenloser Versand DE</span></div>';social.appendChild(e)}
 function refineHomeCopy(){const b=$('#bestsellers .section-head h2');if(b)b.innerHTML='CURATED.<br>ESSENTIALS.';const bp=$('#bestsellers .section-head p');if(bp)bp.textContent='Vier Kern-Pieces. Klare Gewichte, Fits und Farben – ohne unnötige Auswahlhürden.';const bundleH=$('#bundle .section-head h2');if(bundleH)bundleH.innerHTML='BUILD YOUR<br>2-PACK.';const bundleP=$('#bundle .section-head p');if(bundleP)bundleP.textContent='Zwei Formshift Shirts. Farbe und Größe je Shirt separat wählen. Bundle 69,90 €.'}
 function collection(){const c=$('.collection');if(!c||$('.v18-collection-intro'))return;const h=$('h1',c);if(h)h.innerHTML='FORM /<br>MOTION.';const tools=$('.v16-collection-tools',c)||$('.filters',c);const e=document.createElement('div');e.className='v18-collection-intro';e.innerHTML='<p>Heavyweight Pieces nach GSM, Farbe und Fit filtern. Produktbild anklicken, um direkt zur PDP zu gelangen.</p><span class="eye">DESIGNED FOR PRESENCE</span>';tools?.before(e);evt('collection_signature_view')}
 function pdp(){const id=productId();if(!id||typeof PRODUCTS==='undefined')return;const p=PRODUCTS[id],info=$('.pdp-info'),grid=$('.pdp-grid');if(!info||!grid||$('.v18-pdp-kicker'))return;const kicker=document.createElement('div');kicker.className='v18-pdp-kicker';kicker.innerHTML=`<span>FORM / MOTION · ${p.gsm} GSM</span><span>${p.fit}</span>`;info.insertBefore(kicker,info.firstChild);const specs=$('.specs',info),values=document.createElement('div');values.className='v18-value-stack';values.innerHTML=`<div><b>${p.gsm} GSM</b><span>Materialgewicht</span></div><div><b>${p.fit}</b><span>Silhouette</span></div><div><b>2–4 WT</b><span>Lieferzeit DE</span></div><div><b>30 Tage</b><span>Rückgabe</span></div>`;if(specs)specs.after(values);const ctas=$('.pdp-ctas',info),utility=document.createElement('div');utility.className='v18-pdp-utility';utility.innerHTML='<div><b>VERSAND</b>4,90 € · kostenlos ab 50 €</div><div><b>RÜCKGABE</b>30 Tage</div><div><b>PAYMENT</b>Native Shopify Payments im Live-Theme</div>';ctas?.after(utility);
   const modules=['.v17-fit-proof','.v17-material-proof','.v17-video-proof','.v17-review-intel','.v17-objection'].map(s=>$(s,info)).filter(Boolean);const story=document.createElement('section');story.className='v18-pdp-story';story.innerHTML=`<div class="v18-pdp-story-head"><div class="eye">PRODUCT STORY</div><h2>SEE THE<br>DETAILS.</h2><p class="micro">Fit, Material, Bewegung und echte Review-Daten an einem Ort – ohne die Kaufentscheidung oben zu überladen.</p></div><div class="v18-pdp-media-story"></div>`;grid.after(story);const media=$('.v18-pdp-media-story',story),color=p.colors[0],g=p.gallery[color]||[];(g.length?g:[p.gallery[p.colors[0]][0]]).slice(0,4).forEach((u,i)=>{const img=document.createElement('img');img.src=u+(u.includes('?')?'&':'?')+'width=1000';img.loading='lazy';img.width=1000;img.height=1250;img.alt=`${p.short} Ansicht ${i+1}`;media.appendChild(img)});modules.forEach(m=>story.appendChild(m));evt('pdp_signature_story',{product:id})}
 function cart(){const page=$('.cart-page');if(!page||$('.v18-cart-header'))return;const e=document.createElement('div');e.className='v18-cart-header';e.innerHTML='<h2>YOUR BAG.</h2><p>Produkte, Varianten, Versand und Rückgabe klar zusammengefasst.</p>';const layout=$('.cart-layout',page);layout?.before(e);evt('cart_signature_view')}
 function cleanLabels(){const slot=$('.v17-home-proof-note');if(slot)slot.textContent='Live-Social-Proof wird ausschließlich aus verbundenen Loox-/Creator-Daten befüllt.';$$('.v17-ugc-slot').forEach(x=>x.textContent='LIVE UGC SLOT')}
 function run(){ready();hero();homeStrip();setTimeout(()=>{reorderHome();refineHomeCopy();spotlight();proofFacts();collection();pdp();cart();cleanLabels()},140);evt('v18_loaded',{path:location.pathname})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
