(function(){
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const coarse=matchMedia('(pointer: coarse)').matches;
 const productFromPath=()=>{const m=location.pathname.match(/product-(shirt|hoodie|pants|zipper)/);return m?m[1]:null};
 const evt=(name,props={})=>{if(typeof track==='function')track(name,{...props,v19:true})};
 function addCss(){if($('link[data-v19]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='v19.css';l.dataset.v19='1';document.head.appendChild(l)}
 function progress(){const b=document.createElement('div');b.className='v19-progress';document.body.appendChild(b);let raf=0;const draw=()=>{raf=0;const max=document.documentElement.scrollHeight-innerHeight;const p=max>0?Math.max(0,Math.min(1,scrollY/max)):0;b.style.setProperty('--v19-progress',(p*100).toFixed(2)+'%')};addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(draw)},{passive:true});draw()}
 function cursorOrb(){if(coarse||reduced)return;const o=document.createElement('div');o.className='v19-cursor-orb';document.body.appendChild(o);addEventListener('pointermove',e=>{o.style.left=e.clientX+'px';o.style.top=e.clientY+'px';o.classList.add('on')},{passive:true});document.documentElement.addEventListener('mouseleave',()=>o.classList.remove('on'))}
 function reveals(){if(reduced)return;const nodes=$$('section,.card,.v17-ugc-card,.v18-spotlight-copy').filter((n,i)=>i<40);nodes.forEach(n=>n.classList.add('v19-reveal'));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-in');io.unobserve(e.target)}}),{rootMargin:'0px 0px -8% 0px',threshold:.08});nodes.forEach(n=>io.observe(n))}
 function heroParallax(){const media=$('.hero-media');if(!media)return;const imgs=$$('img',media);const hint=document.createElement('div');hint.className='v19-hero-hint';hint.textContent=coarse?'SWIPE · MOVE':'MOVE · EXPLORE';media.appendChild(hint);let tx=50,ty=34,rx=0,ry=0,raf=0;const paint=()=>{raf=0;media.style.setProperty('--v19-x',tx+'%');media.style.setProperty('--v19-y',ty+'%');if(!reduced&&!coarse)imgs.forEach((im,i)=>im.style.transform=`translate3d(${rx*(i?-.45:1)}px,${ry*(i?-.45:1)}px,0) scale(${i?1.006:1.012})`)};if(!coarse){media.addEventListener('pointermove',e=>{const r=media.getBoundingClientRect();tx=((e.clientX-r.left)/r.width)*100;ty=((e.clientY-r.top)/r.height)*100;rx=(tx-50)*.11;ry=(ty-50)*.08;if(!raf)raf=requestAnimationFrame(paint)},{passive:true});media.addEventListener('pointerleave',()=>{tx=50;ty=34;rx=ry=0;if(!raf)raf=requestAnimationFrame(paint)})}else{let sx=0;media.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});media.addEventListener('touchmove',e=>{const d=Math.max(-40,Math.min(40,e.touches[0].clientX-sx));imgs.forEach((im,i)=>im.style.transform=`translate3d(${d*(i?-.15:.15)}px,0,0)`)},{passive:true});media.addEventListener('touchend',()=>imgs.forEach(im=>im.style.transform=''),{passive:true})}evt('hero_interactive_ready')}
 function magnetic(){if(coarse||reduced)return;$$('.btn,.v16-card-actions button,.v15-icon').forEach(b=>{b.classList.add('v19-magnetic');b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;b.style.transform=`translate(${x}px,${y}px)`});b.addEventListener('pointerleave',()=>b.style.transform='')})}
 function splitReveal(){const id=productFromPath();if(!id||typeof PRODUCTS==='undefined'||$('.v19-split'))return;const p=PRODUCTS[id],c=p.colors[0],g=p.gallery[c]||[];if(g.length<2)return;const story=$('.v18-pdp-story');if(!story)return;const wrap=document.createElement('div');wrap.innerHTML=`<div class="eye">INTERACTIVE PRODUCT VIEW</div><h3 style="font-size:26px;margin:5px 0 12px">FRONT / BACK</h3><div class="v19-split" style="--split:50%"><img src="${g[0]}&width=1100" loading="lazy" alt="${p.short} Front"><img class="v19-split-back" src="${g[1]}&width=1100" loading="lazy" alt="${p.short} Back"><div class="v19-split-line"></div><button class="v19-split-handle" type="button" aria-label="Front und Back vergleichen">↔</button></div>`;const split=$('.v19-split',wrap),handle=$('.v19-split-handle',wrap);let active=false;const set=x=>{const r=split.getBoundingClientRect(),p=Math.max(5,Math.min(95,((x-r.left)/r.width)*100));split.style.setProperty('--split',p+'%')};handle.addEventListener('pointerdown',e=>{active=true;handle.setPointerCapture(e.pointerId);set(e.clientX);evt('split_reveal_start',{product:id})});handle.addEventListener('pointermove',e=>{if(active)set(e.clientX)});handle.addEventListener('pointerup',e=>{active=false;try{handle.releasePointerCapture(e.pointerId)}catch(_){}});split.addEventListener('click',e=>{if(e.target!==handle)set(e.clientX)});story.insertBefore(wrap,story.children[1]||null)}
 function gsmLab(){if(!/\/v19\/(?:index\.html)?$/.test(location.pathname)&&!location.pathname.endsWith('/v19/'))return;if($('.v19-gsm')||typeof PRODUCTS==='undefined')return;const vals=[240,380,430],ids=['shirt','hoodie','zipper'];const s=document.createElement('section');s.className='v19-gsm';s.innerHTML=`<div class="eye">INTERACTIVE MATERIAL LAB</div><h2>FEEL THE<br>WEIGHT.</h2><p class="micro">Ziehe den Regler und sieh, wie sich Materialgewicht, Produktart und visuelle Substanz verändern.</p><div class="v19-gsm-stage"><div class="v19-gsm-visual"><img alt="Materialvergleich" loading="lazy"></div><div><div class="v19-gsm-copy"><div><strong></strong><span></span></div><span class="eye">GSM</span></div><input type="range" min="0" max="2" step="1" value="0" aria-label="GSM Vergleich"><div class="v19-gsm-labels"><span>240</span><span>380</span><span>430</span></div></div></div>`;const anchor=$('#whyHeavy')||$('#bundle');anchor?.after(s);const range=$('input',s),img=$('img',s),strong=$('strong',s),copy=$('.v19-gsm-copy div span',s);const render=()=>{const i=+range.value,p=PRODUCTS[ids[i]],c=p.colors[0],u=p.gallery[c][0];img.src=u+(u.includes('?')?'&':'?')+'width=900';img.classList.remove('v19-color-flash');void img.offsetWidth;img.classList.add('v19-color-flash');img.style.transform=`scale(${1+i*.035})`;strong.textContent=vals[i];copy.textContent=i===0?'Strukturiertes Shirtgewicht – präsent, aber alltagstauglich.':i===1?'Mehr Volumen, Wärme und ruhigerer Fall für Hoodie/Sweat.':'Maximale Substanz im Zipper – schwerer Look und klare Form.';evt('gsm_lab_change',{gsm:vals[i]})};range.addEventListener('input',render);render()}
 function cardTilt(){if(coarse||reduced)return;$$('.card').forEach(card=>{const media=$('.card-media',card);if(!media)return;media.classList.add('v19-product-tilt');media.addEventListener('pointermove',e=>{const r=media.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;media.style.transform=`perspective(900px) rotateY(${x*4}deg) rotateX(${-y*4}deg)`});media.addEventListener('pointerleave',()=>media.style.transform='')})}
 function swatchReaction(){document.addEventListener('click',e=>{const b=e.target.closest('#pdpColors button,.v16-swatch,[data-v16-filter]');if(!b)return;const img=$('#mainImg')||$('.hero-media img.front');if(img){img.classList.remove('v19-color-flash');void img.offsetWidth;img.classList.add('v19-color-flash')}showToastMini('LOOK UPDATED')},{passive:true})}
 function showToastMini(text){let t=$('.v19-toast');if(!t){t=document.createElement('div');t.className='v19-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),900)}
 function kinetic(){if(!/\/v19\/(?:index\.html)?$/.test(location.pathname)&&!location.pathname.endsWith('/v19/'))return;if($('.v19-kinetic')||!$('.hero'))return;const k=document.createElement('div');k.className='v19-kinetic';const txt='HEAVYWEIGHT · FORM / MOTION · STRUCTURE · OVERSIZED · MOVE DIFFERENT · ';k.innerHTML=`<div class="v19-kinetic-track"><span>${txt}</span><span>${txt}</span></div>`;$('.v18-home-strip')?.after(k)}
 function cartFeedback(){document.addEventListener('click',e=>{if(e.target.closest('#pdpAdd,#stickyAdd,#bundleAdd,#lookAdd,[id=qvAdd]'))showToastMini('ADDED TO BAG ✓')})}
 function init(){addCss();document.documentElement.classList.add('v19-ready');progress();cursorOrb();heroParallax();setTimeout(()=>{gsmLab();splitReveal();reveals();magnetic();cardTilt();kinetic()},180);swatchReaction();cartFeedback();evt('v19_loaded',{path:location.pathname})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
