const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const cart=()=>read('nw14_cart',[]),fit=()=>read('nw14_fit',{}),wish=()=>read('nw14_wish',[]),recent=()=>read('nw14_recent',[]);
function track(event,props={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...props,path:location.pathname,ts:Date.now()})}
function openLayer(id){const e=document.getElementById(id);if(e){e.classList.add('open');document.body.style.overflow='hidden'}}function closeLayer(id){const e=document.getElementById(id);if(e){e.classList.remove('open');document.body.style.overflow=''}}
function countBag(){const n=cart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('[data-count]').forEach(e=>e.textContent=n)}
function src(u,w){return u+(u.includes('?')?'&':'?')+'width='+w}
function setupChrome(){countBag();document.querySelector('[data-menu]')?.addEventListener('click',()=>openLayer('menu'));document.querySelector('[data-search]')?.addEventListener('click',()=>{renderSearch('');openLayer('search')});document.querySelector('[data-cart]')?.addEventListener('click',()=>{renderDrawer();openLayer('drawer');track('cart_drawer_open')});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeLayer(b.dataset.close));document.querySelectorAll('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)closeLayer(o.id)});const i=document.getElementById('searchInput');if(i)i.oninput=()=>renderSearch(i.value)}
function showToast(t){const e=document.getElementById('shipToast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function addCart(id,size,color,qty=1,bundle=false){const c=cart();c.push({id,size,color,qty,bundle});write('nw14_cart',c);countBag();renderDrawer();const sub=c.reduce((s,x)=>s+(x.bundle?34.95:PRODUCTS[x.id].price)*x.qty,0);const gap=Math.max(0,50-sub);showToast(gap?`Noch ${money(gap)} bis kostenloser Versand`:'Kostenloser Versand freigeschaltet ✓');openLayer('drawer');track('add_to_cart',{product:id,size,color,bundle});if(sub>=50)track('free_shipping_reached',{value:sub})}
function pushRecent(id){let r=recent().filter(x=>x!==id);r.unshift(id);write('nw14_recent',r.slice(0,8))}
function toggleWish(id){let w=wish();w=w.includes(id)?w.filter(x=>x!==id):[...w,id];write('nw14_wish',w);track('wishlist_toggle',{product:id,active:w.includes(id)});renderMemory()}
function recommend(p){const f=fit();return f.rec&&p.sizes.includes(f.rec)?f.rec:p.sizes[Math.min(2,p.sizes.length-1)]}
function quickView(id){const p=PRODUCTS[id];pushRecent(id);const color=p.colors[0],g=p.gallery[color],h=document.getElementById('qvBody'),rec=recommend(p);h.innerHTML=`<div class="qv-gallery">${g.map(u=>`<img src="${src(u,800)}" loading="lazy">`).join('')}</div><div class="eye" style="color:#666;margin-top:10px">${p.gsm} GSM · ${p.fit}</div><h2 style="font-size:32px;line-height:.92;margin:6px 0">${p.short}</h2><div style="font-size:20px">${money(p.price)}</div><div style="color:#47652d;margin:7px 0">Empfohlen: <b>${rec}</b></div><div class="qv-options"><select id="qvS">${p.sizes.map(s=>`<option ${s===rec?'selected':''}>${s}</option>`).join('')}</select><select id="qvC">${p.colors.map(c=>`<option>${c}</option>`).join('')}</select></div>${id==='shirt'?'<div class="micro" style="margin:8px 0">2er Bundle: 69,90 € · Farben & Größen frei kombinierbar</div>':''}<button class="btn primary" style="width:100%;border-color:#111" id="qvAdd">IN DEN WARENKORB</button>`;document.getElementById('qvC').onchange=e=>{const col=e.target.value,imgs=p.gallery[col];h.querySelector('.qv-gallery').innerHTML=imgs.map(u=>`<img src="${src(u,800)}" loading="lazy">`).join('');track('variant_select',{product:id,color:col,source:'quick_view'})};document.getElementById('qvAdd').onclick=()=>addCart(id,document.getElementById('qvS').value,document.getElementById('qvC').value);openLayer('quick');track('quick_view_open',{product:id});renderMemory()}
function smartFilter(q,p){q=q.toLowerCase().trim();if(!q)return true;let ok=(p.name+' '+p.gsm+' '+p.fit+' '+p.colors.join(' ')).toLowerCase().includes(q);const m=q.match(/unter\s*(\d+)/);if(m)ok=p.price<Number(m[1]);if(q.includes('schwarz'))ok=p.colors.includes('Schwarz');if(q.includes('hoodie'))ok=p.id==='hoodie'||p.id==='zipper';if(q.includes('shirt'))ok=p.id==='shirt';if(q.includes('pants')||q.includes('hose'))ok=p.id==='pants';return ok}
function renderSearch(q){const h=document.getElementById('searchResults');if(!h)return;h.innerHTML=Object.values(PRODUCTS).filter(p=>smartFilter(q,p)).map(p=>`<a class="search-card" href="product-${p.id}.html"><img src="${src(p.gallery[p.colors[0]][0],320)}"><div><b>${p.short}</b><div>${p.gsm} GSM · ${money(p.price)}</div><small>Fit: ${recommend(p)}</small></div></a>`).join('')||'<p>Keine Treffer.</p>';renderMemory()}
function renderMemory(){const rh=document.getElementById('searchRecent'),wh=document.getElementById('searchWish');const card=id=>{const p=PRODUCTS[id];return `<button class="memory-chip" onclick="quickView('${id}')"><img src="${src(p.gallery[p.colors[0]][0],280)}"><b>${p.short}</b></button>`};if(rh)rh.innerHTML=recent().map(card).join('')||'<span class="micro">Noch nichts angesehen.</span>';if(wh)wh.innerHTML=wish().map(card).join('')||'<span class="micro">Wishlist leer.</span>'}
function renderDrawer(){const h=document.getElementById('drawerBody');if(!h)return;const c=cart();if(!c.length){h.innerHTML='<p>Dein Bag ist leer.</p><a class="btn primary" style="border-color:#111" href="collection.html">SHOPPEN</a>';return}const sub=c.reduce((s,x)=>s+(x.bundle?34.95:PRODUCTS[x.id].price)*x.qty,0),gap=Math.max(0,50-sub),ids=[...new Set(c.map(x=>x.id))];let up='';if(ids.includes('shirt')&&!ids.includes('pants'))up='pants';else if(ids.includes('pants')&&!ids.includes('hoodie'))up='hoodie';else if(!ids.includes('zipper'))up='zipper';if(ids.includes(up))up='';h.innerHTML=c.map(x=>`<div class="cart-item"><img src="${src(PRODUCTS[x.id].gallery[x.color]?.[0]||PRODUCTS[x.id].gallery[PRODUCTS[x.id].colors[0]][0],260)}"><div><b>${PRODUCTS[x.id].short}</b><div>${x.size} · ${x.color}</div></div><strong>${money((x.bundle?34.95:PRODUCTS[x.id].price)*x.qty)}</strong></div>`).join('')+`<div class="progress"><i style="width:${Math.min(100,sub/50*100)}%"></i></div><p>${gap?`Noch ${money(gap)} bis kostenloser Versand`:'Kostenloser Versand ✓'}</p>${up?`<div class="upsell"><img src="${src(PRODUCTS[up].gallery[PRODUCTS[up].colors[0]][0],240)}"><div><b>Passt dazu</b><div>${PRODUCTS[up].short}</div></div><button onclick="addCart('${up}','${recommend(PRODUCTS[up])}','${PRODUCTS[up].colors[0]}')">+</button></div>`:''}<div style="display:flex;justify-content:space-between;font-size:18px;margin-top:10px"><b>Gesamt</b><b>${money(sub)}</b></div><a class="btn primary" style="width:100%;border-color:#111;margin-top:10px" href="cart.html">ZUM WARENKORB</a>`}
