(function(){
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const productId=()=>{const m=location.pathname.match(/product-(shirt|hoodie|pants|zipper)/);return m?m[1]:null};
 const isHome=()=>/\/v22\/(?:index\.html)?$/.test(location.pathname)||location.pathname.endsWith('/v22/');
 const event=(name,props={})=>{if(typeof track==='function')track(name,{...props,v22:true})};
 const reviewData=id=>window.NOVAWEAR_REVIEW_DATA?.[id]||null;
 const url=(u,w=900)=>u+(u.includes('?')?'&':'?')+'width='+w;
 function addNavigation(){const nav=$('.nav');if(nav&&!nav.querySelector('[href="archive.html"]')){const bag=nav.querySelector('[href="cart.html"]');[['FIT GUIDE','fit-guide.html'],['ARCHIVE','archive.html']].forEach(([t,h])=>{const a=document.createElement('a');a.textContent=t;a.href=h;nav.insertBefore(a,bag)})}const menu=$('#menu .cards');if(menu&&!menu.querySelector('[href="archive.html"]'))menu.insertAdjacentHTML('beforeend','<a class="card-body" href="fit-guide.html">FIT GUIDE</a><a class="card-body" href="archive.html">ARCHIVE</a>');const mega=$('.v16-mega');if(mega&&!mega.querySelector('[href="archive.html"]')){const d=[...mega.querySelectorAll('div')].find(x=>x.querySelector('h4')?.textContent==='DISCOVER');d?.insertAdjacentHTML('beforeend','<a href="fit-guide.html">Fit Guide</a><a href="archive.html">Campaign Archive</a>')}const f=$('.v16-footer');if(f&&!f.querySelector('[href="archive.html"]'))f.querySelector('.v16-footer-grid>div:first-child')?.insertAdjacentHTML('beforeend','<p><a href="fit-guide.html">Fit Guide</a> · <a href="archive.html">Archive</a></p>')}
 function benchmarkStrip(){if(!isHome()||$('.v22-benchmark-strip'))return;const anchor=$('.v20-hero-shell')||$('.hero');if(!anchor)return;const e=document.createElement('div');e.className='v22-benchmark-strip';e.innerHTML='<div><b>FIT FIRST</b><span>Größe & Silhouette verstehen</span></div><div><b>REAL PROOF</b><span>Reviews nur aus Live-Daten</span></div><div><b>2–4 WERKTAGE</b><span>Lieferung innerhalb DE</span></div><div><b>30 TAGE</b><span>Rückgabe</span></div>';anchor.after(e)}
 function discovery(){if(!isHome()||$('.v22-discovery')||typeof PRODUCTS==='undefined')return;const ids=['shirt','hoodie','pants','zipper'],s=document.createElement('section');s.className='v22-discovery';s.innerHTML='<div class="eye">SHOP BY PIECE</div><h2>FIND YOUR<br>FORM.</h2><div class="v22-discovery-grid"></div>';const g=$('.v22-discovery-grid',s);ids.forEach(id=>{const p=PRODUCTS[id],c=p.colors[0],u=p.gallery[c][0],a=document.createElement('a');a.className='v22-discovery-card';a.href=`product-${id}.html`;a.innerHTML=`<img src="${url(u,900)}" loading="lazy" alt="${p.short}"><footer><b>${p.short}</b><span>${p.gsm} GSM · ${p.fit} · ${money(p.price)}</span></footer>`;g.appendChild(a)});($('#bestsellers')||$('#bundle'))?.after(s)}
 function personalAccess(){if(!isHome()||$('.v22-access'))return;const saved=typeof wish==='function'?wish().length:0,f=typeof fit==='function'?fit():{};const s=document.createElement('section');s.className='v22-access';s.innerHTML=`<div class="eye" style="color:#666">PERSONAL SHOPPING</div><h2>YOUR FIT.<br>YOUR EDIT.</h2><p>Die stärksten Shops reduzieren Entscheidungslast. NOVAWEAR speichert deshalb deine Fit-Empfehlung und deine Saved Pieces lokal auf diesem Gerät – ohne erfundene Loyalty-Vorteile.</p><div class="v22-access-grid"><div class="v22-access-card"><b>FIT MEMORY</b><span>${f.rec?`Gespeicherte Empfehlung: ${f.rec}. Auf kompatiblen PDPs direkt verfügbar.`:'Noch keine Größe gespeichert. Nutze Fit Scan als Orientierung.'}</span><a href="index.html#fitSection">FIT SCAN</a></div><div class="v22-access-card"><b>SAVED PIECES</b><span>${saved?`${saved} Piece${saved===1?'':'s'} gespeichert.`:'Noch keine Pieces gespeichert.'}</span><a href="saved.html">SAVED ÖFFNEN</a></div><div class="v22-access-card"><b>EARLY ACCESS</b><span>Neue Drops und Kampagnen zuerst entdecken. Newsletter-Anbindung bleibt im Live-Shop der echte Opt-in.</span><a href="index.html#earlyAccess">EARLY ACCESS</a></div></div>`;($('#fitSection')||$('#lookBuilder'))?.after(s)}
 function sizeFilter(){const tools=$('.v16-collection-tools'),grid=$('#grid');if(!tools||!grid||$('.v22-size-filter'))return;const sizes=['XS','S','M','L','XL','XXL','3XL','4XL'],wrap=document.createElement('div');wrap.className='v22-size-filter';wrap.innerHTML='<button class="on" data-size="all">ALLE GRÖSSEN</button>'+sizes.map(s=>`<button data-size="${s}">${s}</button>`).join('');tools.appendChild(wrap);let selected='all';function apply(){$$('.card[data-product]',grid).forEach(card=>{const p=PRODUCTS[card.dataset.product],ok=selected==='all'||p?.sizes?.includes(selected);card.style.display=ok?'':'none'})}$$('[data-size]',wrap).forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.size;$$('[data-size]',wrap).forEach(x=>x.classList.toggle('on',x===b));apply();event('size_filter',{size:selected})}));new MutationObserver(()=>setTimeout(()=>{enhanceQuickAdd();apply()},20)).observe(grid,{childList:true});apply()}
 function enhanceQuickAdd(){const grid=$('#grid');if(!grid||typeof PRODUCTS==='undefined')return;$$('.card[data-product]',grid).forEach(card=>{if($('.v22-quickadd',card))return;const id=card.dataset.product,p=PRODUCTS[id],body=$('.card-body',card);if(!p||!body)return;const box=document.createElement('div');box.className='v22-quickadd';box.innerHTML=`<button class="v22-quickadd-trigger" type="button">QUICK ADD</button><div class="v22-quickadd-sizes">${p.sizes.slice(0,8).map(s=>`<button type="button" data-qsize="${s}">${s}</button>`).join('')}</div>`;body.appendChild(box);$('.v22-quickadd-trigger',box).onclick=()=>{box.classList.toggle('open');event('quick_add_open',{product:id})};$$('[data-qsize]',box).forEach(b=>b.onclick=()=>{addCart(id,b.dataset.qsize,p.colors[0]);event('quick_add',{product:id,size:b.dataset.qsize,color:p.colors[0]})})})}
 function fitConsensus(id,p,host){if($('.v22-fit-consensus',host))return;const d=reviewData(id),reviews=d?.reviews||[],fits=reviews.map(r=>String(r.fit||r.fitRating||r.passform||'').toLowerCase()).filter(Boolean),sizes=reviews.map(r=>r.size).filter(Boolean);let fitLabel='',fitN=0;if(fits.length){const groups={small:0,true:0,large:0};fits.forEach(v=>{if(/small|klein|eng|tight/.test(v))groups.small++;else if(/large|groß|gross|weit|wide|roomy/.test(v))groups.large++;else groups.true++});const key=Object.entries(groups).sort((a,b)=>b[1]-a[1])[0];fitN=key[1];fitLabel={small:'fällt eher klein aus',true:'fällt überwiegend erwartungsgemäß aus',large:'fällt eher groß aus'}[key[0]]}let topSize='';if(sizes.length){const m={};sizes.forEach(s=>m[s]=(m[s]||0)+1);topSize=Object.entries(m).sort((a,b)=>b[1]-a[1])[0][0]}const e=document.createElement('div');e.className='v22-fit-consensus';e.innerHTML=`<div class="v22-fit-consensus-head"><div><div class="eye">FIT CONSENSUS</div><h3>Größe mit weniger Unsicherheit.</h3></div><span class="v22-fit-badge">LIVE REVIEW DATA</span></div>${reviews.length>=3?`<div class="v22-fit-consensus-grid"><div><b>${fitLabel||'Fit-Daten verfügbar'}</b><span>${fitN} von ${fits.length||reviews.length} ausgewerteten Fit-Signalen</span></div><div><b>${topSize||'—'}</b><span>häufig genannte/gekaufte Größe in verbundenen Reviews</span></div><div><b>${d.rating?d.rating.toFixed(1)+' ★':'LIVE'}</b><span>${d.count||reviews.length} verbundene Bewertungen</span></div></div>`:'<div class="v22-fit-empty">Noch nicht genügend Live-Review-Daten für eine belastbare Fit-Aussage. Bis dahin bleiben Model-Referenz, Size Guide und Fit Scan die Orientierung.</div>'}`;host.appendChild(e)}
 function craftStory(id,p,host){if($('.v22-craft',host))return;const model={shirt:'181 cm · 78 kg · M',hoodie:'187 cm · 86 kg · XL',pants:'184 cm · 82 kg · L',zipper:'188 cm · 88 kg · XL'}[id];const mat=id==='shirt'?'100 % Baumwolle':'80 % Baumwolle / 20 % Polyester',detail=id==='shirt'?'Oversized · Drop Shoulders':id==='pants'?'Relaxed Oversized Fit':id==='zipper'?'Oversized · Full Zip':'Oversized · Heavy Hood',e=document.createElement('div');e.className='v22-craft';e.innerHTML=`<div class="eye">PRODUCT ANATOMY</div><h3>Material. Fit. Details. Model.</h3><div class="v22-craft-grid"><div><b>MATERIAL</b><span>${p.gsm} GSM · ${mat}</span></div><div><b>PASSFORM</b><span>${p.fit}</span></div><div><b>DETAILS</b><span>${detail}</span></div><div><b>MODEL</b><span>${model}</span></div></div>`;host.appendChild(e)}
 function getLook(id,p,host){if($('.v22-getlook',host))return;const comp={shirt:'pants',hoodie:'pants',pants:'hoodie',zipper:'shirt'}[id],q=PRODUCTS[comp],c=q.colors[0],e=document.createElement('div');e.className='v22-getlook';e.innerHTML=`<div class="eye" style="color:#666">COMPLETE THE LOOK</div><h3>Get the look.</h3><div class="v22-getlook-card"><img src="${url(q.gallery[c][0],360)}" loading="lazy" alt="${q.short}"><div><b>${q.short}</b><span>${q.gsm} GSM · ${q.fit} · ${money(q.price)}</span><div class="v22-getlook-controls"><select aria-label="Größe wählen">${q.sizes.map(s=>`<option>${s}</option>`).join('')}</select><button type="button">ADD</button></div></div></div>`;host.appendChild(e);$('button',e).onclick=()=>{const size=$('select',e).value;addCart(comp,size,c);event('get_the_look_add',{source:id,product:comp,size})}}
 function reviewSummary(id,host){if($('.v22-review-summary',host))return;const d=reviewData(id);const e=document.createElement('div');e.className='v22-review-summary';if(d?.count){const rec=d.recommendPercent??d.recommend??null;e.innerHTML=`<div class="eye" style="color:#666">VERIFIED REVIEW SUMMARY</div><h3>${d.rating?.toFixed?.(1)||d.rating||'—'} ★ · ${d.count} Bewertungen</h3><div class="v22-review-stats"><div><b>${d.rating?.toFixed?.(1)||d.rating||'—'}</b><span>Durchschnitt</span></div><div><b>${rec!=null?rec+'%':'LIVE'}</b><span>${rec!=null?'würden empfehlen':'Empfehlungsquote, wenn verbunden'}</span></div><div><b>LIVE</b><span>Fit / Größe / Material filterbar</span></div></div>`}else e.innerHTML='<div class="eye" style="color:#666">VERIFIED REVIEW SUMMARY</div><h3>Loox Live Connection</h3><p style="font-size:10px;color:#69635c;line-height:1.55">Sterne, Empfehlungsquote und Fit-Signale erscheinen erst mit echten verbundenen Review-Daten.</p>';host.appendChild(e)}
 function enhancePDP(){const id=productId();if(!id||typeof PRODUCTS==='undefined')return;const p=PRODUCTS[id],info=$('.pdp-info'),story=$('.v18-pdp-story')||$('.pdp');if(!info||!story)return;fitConsensus(id,p,info);craftStory(id,p,story);getLook(id,p,story);reviewSummary(id,story);event('benchmark_pdp_ready',{product:id})}
 function cartRecommendations(){const list=$('#cartList');if(!list||typeof PRODUCTS==='undefined'||$('.v22-empty-recs'))return;const run=()=>{if(typeof cart!=='function'||cart().length)return;const host=$('.v16-cart-empty')||list;if(!host||$('.v22-empty-recs',host))return;const ids=['shirt','hoodie','pants'],e=document.createElement('div');e.className='v22-empty-recs';e.innerHTML='<h3>START WITH THE ESSENTIALS.</h3><div class="v22-empty-grid">'+ids.map(id=>{const p=PRODUCTS[id],u=p.gallery[p.colors[0]][0];return `<a class="v22-empty-card" href="product-${id}.html"><img src="${url(u,420)}" loading="lazy" alt="${p.short}"><div><b>${p.short}</b><span>${money(p.price)} · ${p.gsm} GSM</span></div></a>`}).join('')+'</div><div class="v22-secure-slot">Zahlungsarten werden im echten Shopify-Checkout dynamisch aus den tatsächlich aktivierten Methoden gerendert.</div>';host.appendChild(e)};setTimeout(run,350);new MutationObserver(()=>setTimeout(run,20)).observe(list,{childList:true,subtree:true})}
 function searchUpgrade(){const links=$('.v21-search-links');if(links&&!links.querySelector('[href="fit-guide.html"]'))links.insertAdjacentHTML('beforeend','<a href="fit-guide.html">FIT GUIDE</a><a href="archive.html">CAMPAIGN ARCHIVE</a>')}
 function pageTitle(){document.title=document.title.replace('V21','V22').replace('V20','V22').replace('V18','V22').replace('V16','V22')}
 function init(){document.documentElement.classList.add('v22-ready');pageTitle();setTimeout(()=>{addNavigation();benchmarkStrip();discovery();personalAccess();sizeFilter();enhanceQuickAdd();enhancePDP();cartRecommendations();searchUpgrade()},650);event('v22_loaded',{path:location.pathname})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
