(function(){
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const home=()=>/\/v23\/(?:index\.html)?$/.test(location.pathname)||location.pathname.endsWith('/v23/');
 const pid=()=>{const m=location.pathname.match(/product-(shirt|hoodie|pants|zipper)/);return m?m[1]:null};
 const fmt=n=>typeof money==='function'?money(n):new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
 const img=(u,w=1000)=>u+(u.includes('?')?'&':'?')+'width='+w;
 const live=()=>window.NOVAWEAR_REVIEW_DATA||null;
 const log=(event,props={})=>{if(typeof track==='function')track(event,{...props,v23:true})};
 function title(){document.title=document.title.replace(/V(?:16|18|20|21|22)/g,'V23')}
 function simplifyNav(){const nav=$('.nav');if(nav){const keep=[['SHOP','collection.html'],['FORM / MOTION','campaign.html'],['JOURNAL','journal.html']];nav.innerHTML=keep.map(([t,h])=>`<a href="${h}">${t}</a>`).join('')}const menu=$('#menu .cards');if(menu)menu.innerHTML='<a class="card-body" href="collection.html">SHOP ALL</a><a class="card-body" href="campaign.html">FORM / MOTION</a><a class="card-body" href="fit-guide.html">FIT GUIDE</a><a class="card-body" href="journal.html">JOURNAL</a><a class="card-body" href="archive.html">ARCHIVE</a><a class="card-body" href="about.html">ABOUT</a><a class="card-body" href="saved.html">SAVED PIECES</a>';$$('.actions .v21-saved-icon').forEach(x=>x.remove())}
 function trust(){if(!home()||$('.v23-trust'))return;const hero=$('.v21-hero-shell')||$('.v20-hero-shell')||$('.hero');if(!hero)return;const e=document.createElement('div');e.className='v23-trust';e.innerHTML='<div><b>2–4 WERKTAGE</b><span>Lieferung DE</span></div><div><b>30 TAGE</b><span>Rückgabe</span></div><div><b>AB 50 €</b><span>kostenloser Versand DE</span></div><div><b>FIT GUIDE</b><span>Größe sicherer wählen</span></div>';hero.after(e)}
 function heroCopy(){if(!home())return;const copy=$('.hero-copy');if(!copy)return;const eye=$('.v21-hero-campaign')||$('.eye',copy);if(eye)eye.textContent='FORM / MOTION · 2026';const p=$('p',copy);if(p)p.textContent='Heavyweight silhouettes for people who want presence without noise.';const primary=$('#heroShop');if(primary){primary.textContent='SHOP THE DROP';primary.onclick=null;primary.addEventListener('click',()=>location.href='collection.html')}const second=$('.hero .cta a');if(second){second.textContent='EXPLORE COLLECTION';second.href='campaign.html'}}
 function bestsellers(){if(!home())return;const sec=$('#bestsellers');if(!sec)return;const h=$('.section-head h2',sec),p=$('.section-head p',sec);if(h)h.innerHTML='SHOP<br>THE DROP.';if(p)p.textContent='Vier Kern-Pieces. Weniger Auswahlstress, mehr Fokus auf Silhouette, Farbe und Material.';$$('.card-media',sec).forEach(media=>{const card=media.closest('.card'),id=card?.dataset.product;if(id&&!media.closest('a')){const a=document.createElement('a');a.href=`product-${id}.html`;media.parentNode.insertBefore(a,media);a.appendChild(media)}})}
 function campaign(){if(!home()||$('.v23-campaign')||typeof PRODUCTS==='undefined')return;const p=PRODUCTS.shirt,g=p.gallery.Schwarz||p.gallery[p.colors[0]],s=document.createElement('section');s.className='v23-campaign';s.innerHTML=`<div class="v23-campaign-grid"><a class="v23-campaign-media" href="campaign.html"><img src="${img(g[1]||g[0],1300)}" loading="lazy" alt="FORM / MOTION Campaign"></a><div class="v23-campaign-copy"><div class="eye">CAMPAIGN 001</div><h2>FORM<br>FOLLOWS<br>MOTION.</h2><p>Heavyweight Streetwear, reduziert auf Substanz, Silhouette und Bewegung.</p><a class="btn primary" href="campaign.html">ENTER CAMPAIGN</a></div></div>`;$('#bestsellers')?.after(s)}
 function education(){if(!home()||$('.v23-product-education')||typeof PRODUCTS==='undefined')return;const p=PRODUCTS.shirt,g=p.gallery.Schwarz||p.gallery[p.colors[0]],s=document.createElement('section');s.className='v23-product-education';s.innerHTML=`<div class="eye">WHY HEAVYWEIGHT</div><h2>FORM.<br>WITH WEIGHT.</h2><div class="v23-edu-grid"><a class="v23-edu-media" href="product-shirt.html"><img src="${img(g[2]||g[0],1200)}" loading="lazy" alt="Formshift Heavyweight Material"></a><div class="v23-edu-points"><div><b>STRUCTURE</b><span>${p.gsm} GSM erzeugen einen ruhigeren, definierteren Fall.</span></div><div><b>SUBSTANCE</b><span>Schwere Baumwolle fühlt sich präsenter und hochwertiger an.</span></div><div><b>OPACITY</b><span>Dichteres Material reduziert Durchscheinen.</span></div><div><b>FORM</b><span>${p.fit} für bewusste Weite statt formloser Silhouette.</span></div><div><a class="btn primary" href="product-shirt.html">DISCOVER FORM SHIFT</a></div></div></div>`;$('.v23-campaign')?.after(s)}
 function reorderBundle(){if(!home())return;const b=$('#bundle'),edu=$('.v23-product-education');if(b&&edu)edu.after(b);const h=$('.section-head h2',b),p=$('.section-head p',b);if(h)h.innerHTML='BUILD YOUR<br>2-PACK.';if(p)p.textContent='Zwei Formshift Shirts. Farbe und Größe je Shirt separat wählen. 69,90 € statt 85,98 €.'}
 function proof(){if(!home()||$('.v23-proof'))return;const data=live();let count=0,total=0;if(data)Object.values(data).forEach(x=>{if(Number(x?.count)>0&&Number(x?.rating)>0){count+=Number(x.count);total+=Number(x.rating)*Number(x.count)}});const agg=count?{count,rating:total/count}:null,s=document.createElement('section');s.className='v23-proof';s.innerHTML=`<div class="eye" style="color:#666">COMMUNITY</div><h2>WORN<br>BY YOU.</h2><p>Fit und Material überzeugen stärker, wenn echte Käufer sie bestätigen. Deshalb zeigt NOVAWEAR hier ausschließlich verifizierte Daten, sobald sie live verbunden sind.</p><div class="v23-proof-grid"><div class="v23-proof-card"><b>${agg?agg.rating.toFixed(1)+' ★':'REVIEWS'}</b><span>${agg?agg.count+' echte Bewertungen':'erscheinen mit Live-Loox-Daten'}</span></div><div class="v23-proof-card"><b>FIT</b><span>gekaufte Größe und Fit-Hinweise aus echten Reviews</span></div><div class="v23-proof-card"><b>UGC</b><span>freigegebene Kunden- und Creator-Medien</span></div><div class="v23-proof-card"><b>VERIFIED</b><span>keine erfundenen Kauf- oder Bewertungszahlen</span></div></div>${agg?'':'<div class="v23-proof-live">Im Produktionsshop bleibt dieser Bereich verborgen, bis echte Review-/UGC-Daten verfügbar sind.</div>'}`;$('#bundle')?.after(s);if(!agg)s.dataset.empty='true'}
 function fitCommerce(){if(!home()||$('.v23-fit-commerce'))return;const fit=$('#fitSection'),look=$('#lookBuilder');if(!fit||!look)return;const s=document.createElement('section');s.className='v23-fit-commerce';s.innerHTML='<div class="section-head"><div><div class="eye">FIT → LOOK</div><h2>FIND<br>YOUR FIT.</h2></div><p>Größe wählen, Silhouette einordnen und direkt einen vollständigen Look zusammenstellen.</p></div><div class="fit-look-grid"></div>';const grid=$('.fit-look-grid',s);fit.parentNode.insertBefore(s,fit);grid.appendChild(fit);grid.appendChild(look);$('.v23-proof')?.after(s)}
 function early(){if(!home())return;const e=$('#earlyAccess'),f=$('.v23-fit-commerce');if(e&&f)f.after(e)}
 function pdp(){const id=pid();if(!id||typeof PRODUCTS==='undefined'||$('.v23-pdp-story'))return;const p=PRODUCTS[id],grid=$('.pdp-grid');if(!grid)return;const info=$('.pdp-info'),rating=live()?.[id];if(info){$$('.micro',info).forEach(m=>{if(/loox|live/i.test(m.textContent))m.remove()});const h=info.querySelector('h1');if(h&&rating?.count){let r=document.createElement('a');r.href='#v23Reviews';r.className='v23-pdp-rating';r.textContent=`${Number(rating.rating).toFixed(1)} ★ · ${Number(rating.count)} Bewertungen`;h.after(r)}}const c=p.colors[0],g=p.gallery[c]||[],s=document.createElement('section');s.className='v23-pdp-story';s.innerHTML='<div class="eye">PRODUCT STORY</div><h2>FIT. MATERIAL.<br>DETAIL. MOTION.</h2><div class="v23-pdp-block"><h3>01 · FIT</h3><div class="v23-pdp-media"></div></div><div class="v23-pdp-block"><h3>02 · MATERIAL & DETAIL</h3><div class="v23-pdp-media"></div></div><div class="v23-pdp-block" id="v23Reviews"></div><div class="v23-pdp-block v23-getlook"></div>';const medias=$$('.v23-pdp-media',s);g.slice(0,2).forEach(u=>medias[0].insertAdjacentHTML('beforeend',`<img src="${img(u,1000)}" loading="lazy" alt="${p.short} Fit">`));g.slice(2,5).forEach(u=>medias[1].insertAdjacentHTML('beforeend',`<img src="${img(u,1000)}" loading="lazy" alt="${p.short} Detail">`));const reviews=$('#v23Reviews',s);reviews.innerHTML=rating?.count?`<div class="v23-review-placeholder"><div class="eye" style="color:#666">03 · REVIEWS</div><h3>${Number(rating.rating).toFixed(1)} ★ · ${Number(rating.count)} Bewertungen</h3><p>Echte Review-Daten werden hier inklusive Fit-/Größensignalen dargestellt.</p></div>`:'<div class="v23-review-placeholder"><div class="eye" style="color:#666">03 · REVIEWS</div><h3>Community Proof</h3><p>Dieser Bereich wird im Live-Shop erst sichtbar, sobald echte Loox-Reviews verfügbar sind.</p></div>';const pair={shirt:'pants',hoodie:'pants',pants:'hoodie',zipper:'shirt'}[id],q=PRODUCTS[pair],look=$('.v23-getlook',s);look.innerHTML=`<div class="eye">04 · COMPLETE THE LOOK</div><h3>${q.short}</h3><div class="v23-pdp-media"><a href="product-${pair}.html"><img src="${img(q.gallery[q.colors[0]][0],800)}" loading="lazy" alt="${q.short}"></a></div><a class="btn primary" href="product-${pair}.html">GET THE LOOK</a>`;grid.after(s);$$('.v18-pdp-story,.v20-product-story,.v21-pdp-liveproof,.v22-craft,.v22-review-summary,.v22-getlook').forEach(x=>x.style.display='none');log('v23_pdp_architecture',{product:id})}
 function removeDebugCopy(){if(!home())return;$$('.v17-home-proof-note,.v21-community-live,.v22-secure-slot').forEach(x=>x.remove())}
 function run(){document.documentElement.classList.add('v23-ready');title();setTimeout(()=>{simplifyNav();heroCopy();trust();bestsellers();campaign();education();reorderBundle();proof();fitCommerce();early();pdp();removeDebugCopy()},950);log('v23_loaded',{path:location.pathname})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
