(function(){
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const img=(u,w=1000)=>u+(u.includes('?')?'&':'?')+'width='+w;
 const fmt=n=>typeof money==='function'?money(n):new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
 const log=(event,props={})=>{if(typeof track==='function')track(event,{...props,v25:true})};
 function header(){const h=$('.v25-header');if(!h)return;let raf=0;const draw=()=>{raf=0;h.classList.toggle('is-fixed',scrollY>36)};addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(draw)},{passive:true});draw();const menu=$('.v25-mobile-sheet');$('[data-v25-menu]')?.addEventListener('click',()=>{menu?.classList.add('open');document.body.style.overflow='hidden'});$('[data-v25-close]')?.addEventListener('click',()=>{menu?.classList.remove('open');document.body.style.overflow=''});menu?.addEventListener('click',e=>{if(e.target.closest('a')){menu.classList.remove('open');document.body.style.overflow=''}})}
 function hero(){const hero=$('.v25-hero');if(!hero)return;$$('[data-v25-view]').forEach(b=>b.addEventListener('click',()=>{hero.dataset.view=b.dataset.v25View;$$('[data-v25-view]').forEach(x=>x.classList.toggle('on',x===b));log('hero_view',{view:b.dataset.v25View})}));if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const media=$('.v25-hero-media');media?.addEventListener('pointermove',e=>{const r=media.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$$('img',media).forEach((im,i)=>im.style.transform=`translate3d(${x*(i? -8:8)}px,${y*(i?-5:5)}px,0) scale(1.02)`)});media?.addEventListener('pointerleave',()=>$$('img',media).forEach(im=>im.style.transform=''))}}
 function lower(){if(typeof PRODUCTS==='undefined')return;const p=PRODUCTS.shirt,c1=$('#v25c1'),c2=$('#v25c2'),s1=$('#v25s1'),s2=$('#v25s2'),i1=$('#v25b1'),i2=$('#v25b2');const draw=()=>{if(c1&&i1)i1.src=img((p.gallery[c1.value]||p.gallery[p.colors[0]])[0],700);if(c2&&i2)i2.src=img((p.gallery[c2.value]||p.gallery[p.colors[0]])[0],700)};c1?.addEventListener('change',draw);c2?.addEventListener('change',draw);draw();$('#v25bundle')?.addEventListener('click',()=>{if(typeof addCart==='function'){addCart('shirt',s1.value,c1.value);addCart('shirt',s2.value,c2.value)}log('bundle_add')});const calc=$('#v25calc');calc?.addEventListener('click',()=>{const h=+$('#v25h').value,w=+$('#v25w').value,mode=$('#v25fit').value;let rec='M';if(h>=188||w>=88)rec='XL';else if(h>=183||w>=82)rec='L';else if(h<176&&w<70)rec='S';if(mode==='clean'&&rec==='XL')rec='L';if(mode==='roomy'&&rec==='M')rec='L';$('#v25result').textContent=`Orientierung: ${rec} · ${mode.toUpperCase()}. Für exakte Maße bitte den Fit Guide nutzen.`;log('fit_calculate',{rec,mode})});const proof=$('#v25proof'),data=window.NOVAWEAR_REVIEW_DATA||null;let count=0,total=0;if(data)Object.values(data).forEach(x=>{if(Number(x?.count)>0&&Number(x?.rating)>0){count+=Number(x.count);total+=Number(x.rating)*Number(x.count)}});if(proof){if(count){proof.hidden=false;proof.innerHTML=`<div class="eye">REAL PEOPLE / REAL PROOF</div><h2>WORN<br>BY YOU.</h2><p>Echte Bewertungen, Fit-Signale und Kundenmedien.</p><div class="v24-proof-grid"><div class="v24-proof-card"><b>${(total/count).toFixed(1)} ★</b><span>${count} echte Bewertungen</span></div><div class="v24-proof-card"><b>FIT DATA</b><span>Größe und Passform aus Reviews</span></div><div class="v24-proof-card"><b>UGC</b><span>freigegebene Kunden-/Creator-Medien</span></div><div class="v24-proof-card"><b>VERIFIED</b><span>nur echte Käufe</span></div></div>`}else proof.hidden=true}$('#v25form')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('button').textContent='THANK YOU';log('early_access_demo')})}
 function init(){document.documentElement.classList.add('v24-ready','v25-ready');header();hero();lower();document.title='NOVAWEAR® V25 | Header & Hero System';log('v25_loaded')}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();