(function(){
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const productIdFromPath=()=>{const m=location.pathname.match(/product-(shirt|hoodie|pants|zipper)/);return m?m[1]:null};
 const liveReviews=()=>window.NOVAWEAR_REVIEW_DATA||null;
 function evt(name,props={}){if(typeof track==='function')track(name,{...props,v17:true})}
 function proofbar(){if($('.v17-proofbar'))return;const h=$('.hdr');if(!h)return;const e=document.createElement('div');e.className='v17-proofbar';e.innerHTML='<div><b>HEAVYWEIGHT</b><span>240–430 GSM je Piece</span></div><div><b>2–4 WERKTAGE</b><span>Lieferung innerhalb DE</span></div><div><b>30 TAGE</b><span>Rückgaberecht</span></div><div><b>AB 50 €</b><span>kostenloser Versand DE</span></div>';h.insertAdjacentElement('afterend',e)}
 function liveSummary(id,where){const data=liveReviews()?.[id];const e=document.createElement('div');e.className='v17-inline-proof';if(data&&data.count){e.innerHTML=`<span class="v17-live-rating" data-state="live"><strong>${data.rating.toFixed(1)} ★</strong><span>${data.count} echte Bewertungen</span></span><button class="v17-proof-link" data-scroll-reviews>Bewertungen ansehen</button>`}else{e.innerHTML='<span class="v17-live-rating" data-state="empty"><strong>LOOX LIVE</strong><span>Bewertungen werden nach Live-Verbindung hier angezeigt</span></span>'}where.appendChild(e);e.querySelector('[data-scroll-reviews]')?.addEventListener('click',()=>$('#v17Reviews')?.scrollIntoView({behavior:'smooth'}));}
 function confidence(p,host){const e=document.createElement('div');e.className='v17-pdp-confidence';e.innerHTML=`<div class="v17-confidence-line"><i></i><div><b>${p.gsm} GSM Material</b><span>strukturierter Fall und spürbare Substanz</span></div></div><div class="v17-confidence-line"><i></i><div><b>2–4 Werktage</b><span>klare Lieferzeit innerhalb Deutschlands</span></div></div><div class="v17-confidence-line"><i></i><div><b>30 Tage Rückgabe</b><span>mehr Sicherheit bei Fit und Größe</span></div></div>`;host.appendChild(e)}
 function fitProof(id,p,host){const refs={shirt:[['181 / 78','M','Oversized'],['176 / 70','S','Clean oversized'],['188 / 88','XL','Relaxed']],hoodie:[['187 / 86','XL','Oversized'],['180 / 76','M','Clean'],['193 / 94','XXL','Roomy']],pants:[['184 / 82','L','Relaxed'],['177 / 70','M','Clean'],['190 / 92','XL','Roomy']],zipper:[['188 / 88','XL','Oversized'],['180 / 75','M','Clean'],['194 / 96','XXL','Roomy']]}[id];const e=document.createElement('div');e.className='v17-fit-proof';e.innerHTML=`<div class="v17-fit-proof-head"><div class="eye">FIT PROOF</div><h3>So kannst du den Fit einordnen.</h3><div class="v17-live-only">Referenzwerte für die Demo – keine Kundenbewertungen.</div></div><div class="v17-fit-cards">${refs.map((r,i)=>`<div class="v17-fit-card"><div class="num">0${i+1}</div><div><b>${r[0]} · Körpergröße cm / kg</b><span>${r[2]}</span></div><em>${r[1]}</em></div>`).join('')}</div>`;host.appendChild(e)}
 function materialProof(p,host){const e=document.createElement('div');e.className='v17-material-proof';e.innerHTML=`<div class="eye">MATERIAL PROOF</div><h3>Was ${p.gsm} GSM für den Look bedeutet.</h3><div class="v17-material-proof-grid"><div><b>01</b><span>Mehr Struktur im Fall</span></div><div><b>02</b><span>Weniger Durchscheinen</span></div><div><b>03</b><span>Substanziellere Haptik</span></div></div>`;host.appendChild(e)}
 function videoProof(host){const e=document.createElement('div');e.className='v17-video-proof';e.innerHTML='<div class="eye">VIDEO PROOF</div><h3>Fit · Stoff · Bewegung</h3><div class="v17-video-slots"><div class="v17-video-slot">FIT CLIP SLOT</div><div class="v17-video-slot">FABRIC CLOSE-UP SLOT</div><div class="v17-video-slot">BACKPRINT / MOTION SLOT</div></div><div class="v17-live-only">Im Live-Shop werden hier echte Produkt-/Creator-Clips eingebunden.</div>';host.appendChild(e)}
 function reviewIntel(id,host){const data=liveReviews()?.[id];const e=document.createElement('div');e.className='v17-review-intel';e.id='v17Reviews';e.innerHTML=`<div class="eye" style="color:#666">REVIEW INTELLIGENCE</div><h3>Fit aus echten Bewertungen verstehen.</h3><div class="v17-review-controls"><button class="on" data-rf="all">ALLE</button><button data-rf="fit">FIT</button><button data-rf="size">GRÖSSE</button><button data-rf="material">MATERIAL</button></div><div class="v17-review-state"></div>`;host.appendChild(e);const state=$('.v17-review-state',e);function render(kind='all'){if(!data||!data.reviews?.length){state.innerHTML='Noch keine Live-Review-Daten verbunden. Sobald Loox angebunden ist, werden hier verifizierte Bewertungen inklusive gekaufter Größe, Fit-Hinweisen und optionalen Körpermaßen dargestellt.';return}let arr=data.reviews;if(kind!=='all')arr=arr.filter(r=>(r.tags||[]).includes(kind));state.innerHTML=`<div class="v17-review-live-grid">${arr.slice(0,6).map(r=>`<article class="v17-review-card"><div class="v17-review-card-top"><b>${r.rating||5} ★ · verifizierter Kauf</b><span>${r.size?`Größe ${r.size}`:''}</span></div><p>${r.text||''}</p>${r.height?`<small>${r.height} cm${r.weight?` · ${r.weight} kg`:''}</small>`:''}</article>`).join('')}</div>`}$$('[data-rf]',e).forEach(b=>b.onclick=()=>{$$('[data-rf]',e).forEach(x=>x.classList.toggle('on',x===b));render(b.dataset.rf);evt('review_filter',{product:id,filter:b.dataset.rf})});render()}
 function objections(p,host){const e=document.createElement('div');e.className='v17-objection';e.innerHTML=`<details><summary>Ist ${p.gsm} GSM zu schwer für den Alltag?</summary><p>Das Gewicht beschreibt die Materialdichte. Entscheidend ist der Schnitt: Die Pieces sind so ausgelegt, dass der Stoff strukturiert fällt, ohne wie steife Arbeitskleidung zu wirken.</p></details><details><summary>Welche Größe sollte ich wählen?</summary><p>Für den vorgesehenen ${p.fit}-Look deine reguläre Größe wählen. Für einen kompakteren Fit eine Größe kleiner. Zusätzlich kannst du Fit Scan und Size Guide nutzen.</p></details><details><summary>Was, wenn mir der Fit nicht gefällt?</summary><p>Für Deutschland gilt ein 30-tägiges Rückgaberecht. So kannst du Größe und Silhouette in Ruhe prüfen.</p></details>`;host.appendChild(e)}
 function enhancePdp(){const id=productIdFromPath();if(!id||typeof PRODUCTS==='undefined')return;const p=PRODUCTS[id],info=$('.pdp-info');if(!info||$('.v17-pdp-confidence'))return;const name=info.querySelector('h1');if(name)liveSummary(id,name.parentElement);const ctas=$('.pdp-ctas',info);if(ctas){confidence(p,ctas.parentElement);fitProof(id,p,ctas.parentElement);materialProof(p,ctas.parentElement);videoProof(ctas.parentElement);reviewIntel(id,ctas.parentElement);objections(p,ctas.parentElement)}const mob=document.createElement('div');mob.className='v17-social-early';const d=liveReviews()?.[id];mob.innerHTML=d&&d.count?`<b>${d.rating.toFixed(1)} ★ aus ${d.count} Bewertungen</b><span>Verifizierte Käufe · Fit-Hinweise verfügbar</span>`:'<b>FIT + MATERIAL PROOF</b><span>Review-Daten erscheinen nach Loox-Live-Verbindung.</span>';$('.pdp-grid')?.insertBefore(mob,$('.pdp-grid')?.firstChild);const dock=document.createElement('div');dock.className='v17-proof-dock';dock.innerHTML='<b>MEHR SICHERHEIT BEIM KAUF</b><span>Fit-Referenzen · 2–4 WT · 30 Tage Rückgabe</span><button>FIT & REVIEWS ANSEHEN</button>';document.body.appendChild(dock);dock.querySelector('button').onclick=()=>$('#v17Reviews')?.scrollIntoView({behavior:'smooth'});const sticky=document.createElement('div');sticky.className='v17-sticky-proof';sticky.innerHTML='<b>WHY IT WORKS</b><span>Heavyweight-Material + Fit Intelligence + transparente Liefer- und Rückgabebedingungen.</span>';info.appendChild(sticky);evt('proof_system_view',{product:id})}
 function ugcSection(){if($('#v17Ugc')||!$('#socialProof')||typeof PRODUCTS==='undefined')return;const ids=['shirt','hoodie','pants','zipper','shirt'];const colors=['Schwarz','Natural Raw','Schwarz','French Navy','Babyblau'];const labels=['SHIRT / DETAIL','HOODIE / FORM','PANTS / MATERIAL','ZIPPER / STRUCTURE','SHIRT / COLOR'];const s=document.createElement('section');s.className='v17-ugc';s.id='v17Ugc';s.innerHTML=`<div class="v17-ugc-head"><div><div class="eye">WORN / PROOF</div><h2>SEE IT.<br>FEEL IT.</h2></div><p class="micro">Shoppable Creator-/UGC-Struktur. In der Demo mit Produktmaterial belegt; Live werden hier echte freigegebene Kunden-/Creator-Inhalte geladen.</p></div><div class="v17-ugc-scroll">${ids.map((id,i)=>{const p=PRODUCTS[id],c=p.gallery[colors[i]]?colors[i]:p.colors[0],img=p.gallery[c][Math.min(i%3,p.gallery[c].length-1)];return `<a class="v17-ugc-card" href="product-${id}.html"><div class="v17-ugc-slot">CREATOR / UGC SLOT</div><img src="${img}&width=760" loading="lazy"><div class="v17-ugc-meta"><b>${p.short}</b><span>${labels[i]} · ${p.gsm} GSM</span></div></a>`}).join('')}</div>`;$('#socialProof').before(s)}
 function manifesto(){if($('.v17-brand-manifesto')||!$('#v16Story'))return;const s=document.createElement('section');s.className='v17-brand-manifesto';s.innerHTML='<div><div class="eye" style="color:#666">NOVAWEAR®</div><h2>NOT MADE<br>TO BLEND IN.</h2><p>FORM / MOTION steht für Präsenz ohne Überladung: schwere Materialien, klare Silhouetten und Pieces, die über Form statt über laute Logos wirken.</p></div><div class="v17-brand-points"><div><b>SUBSTANCE</b><span>Materialgewicht, das man sieht und spürt.</span></div><div><b>FORM</b><span>Oversized Silhouetten mit klarer Struktur.</span></div><div><b>MOTION</b><span>Streetwear, die in Bewegung genauso funktioniert wie im Stand.</span></div></div>';$('#v16Story').after(s)}
 function collectionProof(){const grid=$('#grid');if(!grid)return;const apply=()=>{$$('.card',grid).forEach(card=>{if($('.v17-collection-card-rating',card))return;const id=card.dataset.product,d=liveReviews()?.[id],body=$('.card-body',card);if(!body)return;const r=document.createElement('div');r.className='v17-collection-card-rating';r.dataset.live=d&&d.count?'true':'false';r.innerHTML=d&&d.count?`<i class="v17-live-dot"></i><strong>${d.rating.toFixed(1)} ★</strong><span>${d.count} Reviews</span>`:'<i class="v17-live-dot"></i><span>Loox Live Reviews</span>';body.insertBefore(r,body.children[2]||null)})};const obs=new MutationObserver(apply);obs.observe(grid,{childList:true,subtree:true});apply()}
 function cartTrust(){const s=$('#cartSummary');if(!s||$('.v17-cart-trust'))return;const e=document.createElement('div');e.className='v17-cart-trust';e.innerHTML='<div><b>2–4 WT</b>Lieferung DE</div><div><b>30 TAGE</b>Rückgabe</div><div><b>AB 50 €</b>Versand frei</div>';s.appendChild(e)}
 function home(){ugcSection();manifesto();const social=$('#socialProof');if(social&&!$('.v17-home-proof-note',social)){const n=document.createElement('div');n.className='v17-home-proof-note v17-live-only';n.textContent='Social-Proof-Flächen sind für echte Loox-/Creator-Daten vorbereitet. Keine erfundenen Bewertungen.';social.appendChild(n)}}
 document.addEventListener('DOMContentLoaded',()=>{proofbar();setTimeout(()=>{home();enhancePdp();collectionProof();cartTrust()},50);evt('v17_loaded',{page:location.pathname})});
 window.NOVAWEAR_V17_setReviewData=function(data){window.NOVAWEAR_REVIEW_DATA=data;location.reload()};
})();
